import { afterAll, beforeEach, describe, expect, it } from "bun:test";
import { join } from "node:path";
import { and, eq } from "drizzle-orm";
import type { PgBoss } from "pg-boss";
import { app } from "@/app";
import { db } from "@/database";
import { auditLog, episodes } from "@/database/schema";
import { VideoRepository } from "@/modules/video/video.repository";
import { QUEUES, startJobQueue } from "@/queue";
import { setStorage } from "@/shared/storage";
import { FakeStorage } from "./fakes/storage";
import { api, createUser, resetDatabase } from "./helpers";

// Real 1-second videos generated by ffmpeg (tests/fixtures/video)
const fixture = (name: string) =>
  Bun.file(join(import.meta.dir, "fixtures/video", name))
    .arrayBuffer()
    .then((buffer) => new Uint8Array(buffer));

type TestUser = Awaited<ReturnType<typeof createUser>>;
let admin: TestUser;
let user: TestUser;
let storage: FakeStorage;
let boss: PgBoss;
let animeId: number;

beforeEach(async () => {
  await resetDatabase();
  admin = await createUser("ADMIN");
  user = await createUser("USER");
  storage = new FakeStorage();
  setStorage(storage);
  boss = await startJobQueue();
  await boss.deleteAllJobs(QUEUES.transcode);
  await boss.deleteAllJobs(QUEUES.cleanup);

  const { data } = await api.anime.post({ title: "Video test" }, { headers: admin.headers });
  animeId = data?.id ?? 0;
  for (const number of [1, 2]) {
    await api.anime({ id: animeId }).episodes.post({ number }, { headers: admin.headers });
  }
});

// Other test files expect the default: no storage configured
afterAll(() => setStorage(null));

const video = (number = 1) => api.anime({ id: animeId }).episodes({ number }).video;
const requestUpload = (size = 20_000, headers = admin.headers, number = 1) =>
  video(number).upload.post({ size }, { headers });
const complete = (headers = admin.headers, number = 1) =>
  video(number).complete.post(undefined, { headers });
const episodeRow = async (number = 1) =>
  (
    await db
      .select()
      .from(episodes)
      .where(and(eq(episodes.animeId, animeId), eq(episodes.number, number)))
  )[0];
const actionsFor = async (episodeId: number) =>
  (
    await db
      .select({ action: auditLog.action })
      .from(auditLog)
      .where(and(eq(auditLog.entityType, "episode"), eq(auditLog.entityId, episodeId)))
      .orderBy(auditLog.id)
  ).map((entry) => entry.action);

describe("video upload", () => {
  it("request → upload to storage → complete → PROCESSING with a transcode job", async () => {
    const ticket = await requestUpload();
    expect(ticket.status).toBe(201);
    expect(ticket.data?.method).toBe("PUT");
    expect((await episodeRow())?.videoStatus).toBe("UPLOADING");

    storage.upload(ticket.data?.uploadUrl ?? "", await fixture("sample.mp4"));
    const { status, data } = await complete();

    expect(status).toBe(200);
    expect(data?.video).toMatchObject({ status: "PROCESSING", progress: 0, error: null });

    const episode = await episodeRow();
    const [job] = await boss.fetch(QUEUES.transcode);
    expect(job?.data).toEqual({ episodeId: episode?.id, sourceKey: episode?.videoSourceKey });
    expect(episode?.videoSourceKey).toStartWith(`episodes/${episode?.id}/source/`);
    expect(await actionsFor(episode?.id ?? 0)).toEqual([
      "episode.create",
      "video.upload_requested",
      "video.uploaded",
    ]);
  });

  for (const name of ["sample.mp4", "sample.webm", "sample.mkv", "sample.mov"]) {
    it(`accepts ${name.split(".")[1]} by its content`, async () => {
      const ticket = await requestUpload();
      storage.upload(ticket.data?.uploadUrl ?? "", await fixture(name));
      expect((await complete()).status).toBe(200);
    });
  }

  it("rejects a non-video uploaded under the video URL, deletes it and marks the episode FAILED", async () => {
    // The presigned URL does not restrict content: only the bytes tell what was uploaded
    const ticket = await requestUpload();
    const key = storage.keyOf(ticket.data?.uploadUrl ?? "");
    storage.upload(
      ticket.data?.uploadUrl ?? "",
      new TextEncoder().encode("<script>alert(1)</script>"),
    );

    const { status, error } = await complete();

    expect(status).toBe(400);
    expect(JSON.stringify(error?.value)).toContain("не является видео");
    expect(storage.objects.has(key)).toBe(false);
    expect(await episodeRow()).toMatchObject({ videoStatus: "FAILED", videoSourceKey: null });
    expect(await boss.fetch(QUEUES.transcode)).toEqual([]);
    expect((await actionsFor((await episodeRow())?.id ?? 0)).at(-1)).toBe("video.rejected");
  });

  it("rejects an object larger than 5 GiB", async () => {
    const ticket = await requestUpload();
    const key = storage.keyOf(ticket.data?.uploadUrl ?? "");
    storage.upload(ticket.data?.uploadUrl ?? "", await fixture("sample.mp4"));
    storage.reportedSizes.set(key, 5 * 1024 ** 3 + 1);

    const { status } = await complete();

    expect(status).toBe(400);
    expect(storage.objects.has(key)).toBe(false);
  });

  it("refuses to complete before the file is in the storage", async () => {
    await requestUpload();
    expect((await complete()).status).toBe(409);
    expect((await episodeRow())?.videoStatus).toBe("UPLOADING");
  });

  it("refuses to complete without a started upload", async () => {
    expect((await complete()).status).toBe(409);
  });

  it("ignores a stale upload after the upload was restarted", async () => {
    const first = await requestUpload();
    const second = await requestUpload();
    // The file goes to the first (now outdated) URL
    storage.upload(first.data?.uploadUrl ?? "", await fixture("sample.mp4"));

    expect((await complete()).status).toBe(409);
    expect(storage.keyOf(second.data?.uploadUrl ?? "")).not.toBe(
      storage.keyOf(first.data?.uploadUrl ?? ""),
    );
  });

  it("does not replace a video that is being transcoded", async () => {
    const ticket = await requestUpload();
    storage.upload(ticket.data?.uploadUrl ?? "", await fixture("sample.mp4"));
    await complete();

    expect((await requestUpload()).status).toBe(409);
  });

  it("schedules the replaced source for deletion when a new upload starts", async () => {
    const ticket = await requestUpload();
    const oldKey = storage.keyOf(ticket.data?.uploadUrl ?? "");
    storage.upload(ticket.data?.uploadUrl ?? "", await fixture("sample.mp4"));
    await complete();
    // Pretend the worker finished
    await db.update(episodes).set({ videoStatus: "READY" }).where(eq(episodes.animeId, animeId));

    expect((await requestUpload()).status).toBe(201);
    const [cleanup] = await boss.fetch(QUEUES.cleanup);
    expect(cleanup?.data).toEqual({ keys: [oldKey] });
  });

  it("validates access and input", async () => {
    expect((await requestUpload(20_000, user.headers)).status).toBe(403);
    expect((await video(1).upload.post({ size: 1 })).status).toBe(401);
    expect((await requestUpload(0)).status).toBe(400);
    expect((await requestUpload(5 * 1024 ** 3 + 1)).status).toBe(400);
    expect((await requestUpload(20_000, admin.headers, 99)).status).toBe(404);
  });

  it("answers 503 when no storage is configured", async () => {
    setStorage(null);
    expect((await requestUpload()).status).toBe(503);
  });

  it("removes the old in-memory upload route", async () => {
    const response = await app.handle(
      new Request("http://localhost/api/media/videos", { method: "POST", headers: admin.headers }),
    );
    expect(response.status).toBe(404);
  });
});

describe("files of deleted episodes", () => {
  it("are scheduled for deletion together with the episode", async () => {
    const episode = await episodeRow(2);
    await api.anime({ id: animeId }).episodes({ number: 2 }).delete(undefined, {
      headers: admin.headers,
    });

    const [cleanup] = await boss.fetch(QUEUES.cleanup);
    expect(cleanup?.data).toEqual({ prefixes: [`episodes/${episode?.id}/`] });
  });

  it("are scheduled for every episode when the whole anime is deleted", async () => {
    const ids = (await db.select().from(episodes).where(eq(episodes.animeId, animeId))).map(
      (row) => `episodes/${row.id}/`,
    );
    await api.anime({ id: animeId }).delete(undefined, { headers: admin.headers });

    const [cleanup] = await boss.fetch<{ prefixes: string[] }>(QUEUES.cleanup);
    expect(cleanup?.data.prefixes.toSorted()).toEqual(ids.toSorted());
  });
});

describe("playback (HLS)", () => {
  const prefix = (id: number) => `episodes/${id}/hls/v1/`;
  const master =
    "#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1020800,RESOLUTION=640x360\n360p/index.m3u8\n";
  const rendition =
    '#EXTM3U\n#EXT-X-MAP:URI="init_0.mp4"\n#EXTINF:6.000000,\nseg_000.m4s\n#EXT-X-ENDLIST\n';

  const makeReady = async (number = 1) => {
    const episode = await episodeRow(number);
    const id = episode?.id ?? 0;
    await storage.write(`${prefix(id)}master.m3u8`, master);
    await storage.write(`${prefix(id)}360p/index.m3u8`, rendition);
    await db
      .update(episodes)
      .set({ videoStatus: "READY", videoHlsPrefix: prefix(id), videoDurationSec: 12 })
      .where(eq(episodes.id, id));
    return id;
  };

  const get = (path: string) => app.handle(new Request(`http://localhost${path}`));
  const base = () => `/api/anime/${animeId}/episodes/1/video`;

  it("serves the master playlist as produced by ffmpeg", async () => {
    await makeReady();
    const response = await get(`${base()}/master.m3u8`);

    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toBe("application/vnd.apple.mpegurl");
    // Relative rendition paths resolve to the sibling API route
    expect(await response.text()).toContain("360p/index.m3u8");
  });

  it("signs segments and the init segment of a rendition playlist", async () => {
    const id = await makeReady();
    const text = await (await get(`${base()}/360p/index.m3u8`)).text();

    expect(text).toContain(`https://storage.test/${prefix(id)}360p/seg_000.m4s?`);
    expect(text).toContain(`#EXT-X-MAP:URI="https://storage.test/${prefix(id)}360p/init_0.mp4?`);
  });

  it("exposes playback and poster URLs on a ready episode only", async () => {
    await makeReady();
    const { data } = await api.anime({ id: animeId }).get();

    const [ready, notReady] = data?.episodes ?? [];
    expect(ready?.video.playbackUrl).toBe(`${base()}/master.m3u8`);
    expect(ready?.video.posterUrl).toContain("poster.jpg");
    expect(notReady?.video).toMatchObject({ status: "NONE", playbackUrl: null, posterUrl: null });
  });

  it("answers 404 until the video is ready", async () => {
    expect((await get(`${base()}/master.m3u8`)).status).toBe(404);
  });

  it("rejects rendition names outside the ladder (no path tricks)", async () => {
    await makeReady();
    expect((await get(`${base()}/..%2Fsource/index.m3u8`)).status).toBe(400);
    expect((await get(`${base()}/480p/index.m3u8`)).status).toBe(404);
  });
});

describe("worker transitions", () => {
  const processing = async (sourceKey: string, hlsPrefix: string | null = null) => {
    const episode = await episodeRow();
    await db
      .update(episodes)
      .set({ videoStatus: "PROCESSING", videoSourceKey: sourceKey, videoHlsPrefix: hlsPrefix })
      .where(eq(episodes.id, episode?.id ?? 0));
    return episode?.id ?? 0;
  };

  it("marks READY and schedules the previous HLS version for deletion", async () => {
    const id = await processing("src-2", "episodes/x/hls/old/");

    const ready = await VideoRepository.markReady(id, "src-2", {
      hlsPrefix: "episodes/x/hls/new/",
      durationSec: 42,
    });

    expect(ready).toBe(true);
    expect(await episodeRow()).toMatchObject({
      videoStatus: "READY",
      videoProgress: 100,
      videoHlsPrefix: "episodes/x/hls/new/",
      videoDurationSec: 42,
    });
    const [cleanup] = await boss.fetch(QUEUES.cleanup);
    expect(cleanup?.data).toEqual({ prefixes: ["episodes/x/hls/old/"] });
  });

  it("does not let a stale job finish an episode whose upload was replaced", async () => {
    const id = await processing("src-new");

    expect(
      await VideoRepository.markReady(id, "src-old", { hlsPrefix: "p/", durationSec: 1 }),
    ).toBe(false);
    await VideoRepository.setProgress(id, "src-old", 50);
    await VideoRepository.markFailed(id, "src-old", "boom");

    expect(await episodeRow()).toMatchObject({
      videoStatus: "PROCESSING",
      videoProgress: 0,
      videoError: null,
    });
  });

  it("records progress and the failure reason for the current source", async () => {
    const id = await processing("src");

    await VideoRepository.setProgress(id, "src", 40);
    expect((await episodeRow())?.videoProgress).toBe(40);

    await VideoRepository.markFailed(id, "src", "ffmpeg exited with 1");
    expect(await episodeRow()).toMatchObject({
      videoStatus: "FAILED",
      videoError: "ffmpeg exited with 1",
    });
  });
});
