import { afterAll, beforeEach, describe, expect, it } from "bun:test";
import { join } from "node:path";
import { and, eq } from "drizzle-orm";
import type { PgBoss } from "pg-boss";
import { app } from "@/app";
import { db } from "@/database";
import { auditLog, episodes } from "@/database/schema";
import { QUEUES, startJobQueue } from "@/queue";
import { setStorage } from "@/shared/storage";
import { FakeStorage } from "./fakes/storage";
import { api, createUser, resetDatabase } from "./helpers";

// Real 1-second videos generated by ffmpeg (tests/fixtures/video)
const fixture = (name: string) =>
  Bun.file(join(import.meta.dir, "fixtures/video", name))
    .arrayBuffer()
    .then((buffer) => new Uint8Array(buffer));

type TestUser = Awaited<ReturnType<typeof createUser>>;
let admin: TestUser;
let user: TestUser;
let storage: FakeStorage;
let boss: PgBoss;
let animeId: number;

beforeEach(async () => {
  await resetDatabase();
  admin = await createUser("ADMIN");
  user = await createUser("USER");
  storage = new FakeStorage();
  setStorage(storage);
  boss = await startJobQueue();
  await boss.deleteAllJobs(QUEUES.transcode);
  await boss.deleteAllJobs(QUEUES.cleanup);

  const { data } = await api.anime.post({ title: "Video test" }, { headers: admin.headers });
  animeId = data?.id ?? 0;
  for (const number of [1, 2]) {
    await api.anime({ id: animeId }).episodes.post({ number }, { headers: admin.headers });
  }
});

// Other test files expect the default: no storage configured
afterAll(() => setStorage(null));

const video = (number = 1) => api.anime({ id: animeId }).episodes({ number }).video;
const requestUpload = (size = 20_000, headers = admin.headers, number = 1) =>
  video(number).upload.post({ size }, { headers });
const complete = (headers = admin.headers, number = 1) =>
  video(number).complete.post(undefined, { headers });
const episodeRow = async (number = 1) =>
  (
    await db
      .select()
      .from(episodes)
      .where(and(eq(episodes.animeId, animeId), eq(episodes.number, number)))
  )[0];
const actionsFor = async (episodeId: number) =>
  (
    await db
      .select({ action: auditLog.action })
      .from(auditLog)
      .where(and(eq(auditLog.entityType, "episode"), eq(auditLog.entityId, episodeId)))
      .orderBy(auditLog.id)
  ).map((entry) => entry.action);

describe("video upload", () => {
  it("request → upload to storage → complete → PROCESSING with a transcode job", async () => {
    const ticket = await requestUpload();
    expect(ticket.status).toBe(201);
    expect(ticket.data?.method).toBe("PUT");
    expect((await episodeRow())?.videoStatus).toBe("UPLOADING");

    storage.upload(ticket.data?.uploadUrl ?? "", await fixture("sample.mp4"));
    const { status, data } = await complete();

    expect(status).toBe(200);
    expect(data?.video).toMatchObject({ status: "PROCESSING", progress: 0, error: null });

    const episode = await episodeRow();
    const [job] = await boss.fetch(QUEUES.transcode);
    expect(job?.data).toEqual({ episodeId: episode?.id, sourceKey: episode?.videoSourceKey });
    expect(episode?.videoSourceKey).toStartWith(`episodes/${episode?.id}/source/`);
    expect(await actionsFor(episode?.id ?? 0)).toEqual([
      "episode.create",
      "video.upload_requested",
      "video.uploaded",
    ]);
  });

  for (const name of ["sample.mp4", "sample.webm", "sample.mkv", "sample.mov"]) {
    it(`accepts ${name.split(".")[1]} by its content`, async () => {
      const ticket = await requestUpload();
      storage.upload(ticket.data?.uploadUrl ?? "", await fixture(name));
      expect((await complete()).status).toBe(200);
    });
  }

  it("rejects a non-video uploaded under the video URL, deletes it and marks the episode FAILED", async () => {
    // The presigned URL does not restrict content: only the bytes tell what was uploaded
    const ticket = await requestUpload();
    const key = storage.keyOf(ticket.data?.uploadUrl ?? "");
    storage.upload(
      ticket.data?.uploadUrl ?? "",
      new TextEncoder().encode("<script>alert(1)</script>"),
    );

    const { status, error } = await complete();

    expect(status).toBe(400);
    expect(JSON.stringify(error?.value)).toContain("не является видео");
    expect(storage.objects.has(key)).toBe(false);
    expect(await episodeRow()).toMatchObject({ videoStatus: "FAILED", videoSourceKey: null });
    expect(await boss.fetch(QUEUES.transcode)).toEqual([]);
    expect((await actionsFor((await episodeRow())?.id ?? 0)).at(-1)).toBe("video.rejected");
  });

  it("rejects an object larger than 5 GiB", async () => {
    const ticket = await requestUpload();
    const key = storage.keyOf(ticket.data?.uploadUrl ?? "");
    storage.upload(ticket.data?.uploadUrl ?? "", await fixture("sample.mp4"));
    storage.reportedSizes.set(key, 5 * 1024 ** 3 + 1);

    const { status } = await complete();

    expect(status).toBe(400);
    expect(storage.objects.has(key)).toBe(false);
  });

  it("refuses to complete before the file is in the storage", async () => {
    await requestUpload();
    expect((await complete()).status).toBe(409);
    expect((await episodeRow())?.videoStatus).toBe("UPLOADING");
  });

  it("refuses to complete without a started upload", async () => {
    expect((await complete()).status).toBe(409);
  });

  it("ignores a stale upload after the upload was restarted", async () => {
    const first = await requestUpload();
    const second = await requestUpload();
    // The file goes to the first (now outdated) URL
    storage.upload(first.data?.uploadUrl ?? "", await fixture("sample.mp4"));

    expect((await complete()).status).toBe(409);
    expect(storage.keyOf(second.data?.uploadUrl ?? "")).not.toBe(
      storage.keyOf(first.data?.uploadUrl ?? ""),
    );
  });

  it("does not replace a video that is being transcoded", async () => {
    const ticket = await requestUpload();
    storage.upload(ticket.data?.uploadUrl ?? "", await fixture("sample.mp4"));
    await complete();

    expect((await requestUpload()).status).toBe(409);
  });

  it("schedules the replaced source for deletion when a new upload starts", async () => {
    const ticket = await requestUpload();
    const oldKey = storage.keyOf(ticket.data?.uploadUrl ?? "");
    storage.upload(ticket.data?.uploadUrl ?? "", await fixture("sample.mp4"));
    await complete();
    // Pretend the worker finished
    await db.update(episodes).set({ videoStatus: "READY" }).where(eq(episodes.animeId, animeId));

    expect((await requestUpload()).status).toBe(201);
    const [cleanup] = await boss.fetch(QUEUES.cleanup);
    expect(cleanup?.data).toEqual({ keys: [oldKey] });
  });

  it("validates access and input", async () => {
    expect((await requestUpload(20_000, user.headers)).status).toBe(403);
    expect((await video(1).upload.post({ size: 1 })).status).toBe(401);
    expect((await requestUpload(0)).status).toBe(400);
    expect((await requestUpload(5 * 1024 ** 3 + 1)).status).toBe(400);
    expect((await requestUpload(20_000, admin.headers, 99)).status).toBe(404);
  });

  it("answers 503 when no storage is configured", async () => {
    setStorage(null);
    expect((await requestUpload()).status).toBe(503);
  });

  it("removes the old in-memory upload route", async () => {
    const response = await app.handle(
      new Request("http://localhost/api/media/videos", { method: "POST", headers: admin.headers }),
    );
    expect(response.status).toBe(404);
  });
});

describe("files of deleted episodes", () => {
  it("are scheduled for deletion together with the episode", async () => {
    const episode = await episodeRow(2);
    await api.anime({ id: animeId }).episodes({ number: 2 }).delete(undefined, {
      headers: admin.headers,
    });

    const [cleanup] = await boss.fetch(QUEUES.cleanup);
    expect(cleanup?.data).toEqual({ prefixes: [`episodes/${episode?.id}/`] });
  });

  it("are scheduled for every episode when the whole anime is deleted", async () => {
    const ids = (await db.select().from(episodes).where(eq(episodes.animeId, animeId))).map(
      (row) => `episodes/${row.id}/`,
    );
    await api.anime({ id: animeId }).delete(undefined, { headers: admin.headers });

    const [cleanup] = await boss.fetch<{ prefixes: string[] }>(QUEUES.cleanup);
    expect(cleanup?.data.prefixes.toSorted()).toEqual(ids.toSorted());
  });
});
